var test={
	"code": "0000",
	"dataObj": {
		"administrative_list": [{
			"administrative_id": 15,
			"desc": "外科是研究外科疾病的发生，发展规律及其临床表现，诊断，预防和治疗的科学，是以手术切除、修补为主要治病手段的专业科室。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "外科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 16,
			"desc": "神经外科是主治由于外伤导致的脑部、脊髓等神经系统的疾病，例如脑出血出血量危及生命,车祸致脑部外伤，或脑部有肿瘤压迫需手术治疗等。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "神经外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 17,
			"desc": "神经外科学从治疗的疾病谱上主要划分为脑肿瘤、脑血管病和功能脑病。采用手术的方法修正神经系统功能异常的医学分支是为功能神经外科学（Functional Neurosurgery），早期亦称生理神经外科学（Physiologic Neurosurgery），或应用神经生理学（Applied Neurophysiology）。手术针对特定的神经根、神经通路或神经元群，旨在有意识地改变其病理过程，重建神经组织的正常功能。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "功能神经外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 18,
			"desc": "胸外科是一门医学专科，专门研究胸腔内器官，主要指食道、肺部、纵隔病变的诊断及治疗，乳腺外科领域也被归入这个专科，其中又以肺外科和食道外科为主。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "胸外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 19,
			"desc": "肝胆外科主要研究肝细胞癌、肝胆管结石、肝炎后肝硬化和重型肝炎所致的急性肝功能衰竭是严重威胁国人健康的重大疾病。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "肝胆外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 20,
			"desc": "乳腺及甲状腺疾病。乳腺疾病包括 乳腺炎，乳腺肿块，乳腺增生，乳腺癌等。。甲状腺疾病包括 甲状腺功能亢进，结节性甲状腺肿及甲状腺腺瘤，甲状腺癌等。。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "乳腺-甲状腺外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 21,
			"desc": "儿外科是新兴的临床学科，主要研究需手术治疗的小儿疾病。一般分为新生儿外科、小儿普外、小儿胸心外科、小儿泌尿外科、小儿神经外科、小儿耳鼻咽喉——头颈外科、小儿骨科等专业科室。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "儿外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 22,
			"desc": "皮肤外科",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "皮外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 23,
			"desc": "脑外科一般指的是神经外科，是医学中最年轻、最复杂而又发展最快的一门学科。以前由于技术的限制，人的脑部手术可以说是一个禁区，然而随着科技的发展，现在已经可以借助先进的显微外科设备开展各种显微神经外科手术。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "脑外科",
			"parent_administrative_id": 47
		}, {
			"administrative_id": 24,
			"desc": "医学科属。包括呼吸内科，消化内科，心血管内科，神经内科，肿瘤科，内分泌科，血液内科，传染病科，小儿科等等等。 内科问诊 呼吸内科：包括的疾病有感冒、肺炎、肺气肿、肺结核、支气管扩张、哮喘、肺癌、肺心病、呼吸衰竭、慢性支气管炎、气胸、肺脓肿、胸腔积液、间质性肺疾病。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "内科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 25,
			"desc": "心内科，即心血管内科，是各级医院大内科为了诊疗心血管血管疾病而设置的一个临床科室，治疗的疾病包括心绞痛、高血压、猝死、心律失常、心力衰竭、早搏、心律不齐、心肌梗死、心肌病、心肌炎、急性心肌梗死等心血管疾病。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "心血管内科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 26,
			"desc": "神经内科是关于神经方面的二级学科。不属于内科概念。主要诊治脑血管疾病（脑梗塞、脑出血）、偏头痛、脑部炎症性疾病（脑炎、脑膜炎）、脊髓炎、癫痫、痴呆、代谢病和遗传病、三叉神经痛、坐骨神经病、周围神经病及重症肌无力等。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "神经内科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 27,
			"desc": "消化内科是研究食管、胃、小肠、大肠、肝、胆及胰腺等疾病为主要内容的临床三级学科。消化内科疾病种类繁多，医学知识面广，操作复杂而精细。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "消化内科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 28,
			"desc": "内分泌科是医院中一个专门治疗内分泌科疾病的地方，主要负责糖尿病、肥胖症、骨质疏松、痛风、脂质代谢紊乱以及甲状腺、垂体、肾上腺、性腺、甲状旁腺等疾病的临床诊治。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "内分泌科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 29,
			"desc": "呼吸内科为现代西医中一个科室。常见病症有肺炎杆菌肺炎、急性肺脓肿、 肺炎球菌肺炎、 哮喘、 金黄色葡萄球菌肺炎 、肺曲菌病 、肺念珠菌病、 肺泡蛋白质沉积症 、疱疹性咽峡炎 、病毒性肺炎 、矽肺 、肺放线菌病 、单纯性肺嗜酸粒细胞浸润症、 哮喘性肺嗜酸粒细胞浸润症、 阻塞性肺气肿 支气管扩张、 脱屑性间质性肺炎 、免疫缺陷者肺炎 、特发性阻塞性细支气管炎伴机化性肺炎 、呼吸性细支气管相关的间质性肺疾病。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "呼吸科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 30,
			"desc": "肾内科是各级医院为了诊疗肾脏病而设置的一个临床科室。常见的肾脏替代治疗方式有肾移植、血液透析和腹膜透析。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "肾病内科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 31,
			"desc": "血液科，又称血液内科，是内科学的分支，主要治疗造血系统疾病，即血液病。在一些医院里常包含在肿瘤科内，统称肿瘤血液科。\n",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "血液科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 32,
			"desc": "血液科，又称血液内科，是内科学的分支，主要治疗造血系统疾病，即血液病。在一些医院里常包含在肿瘤科内，统称肿瘤血液科。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "血液科",
			"parent_administrative_id": 24
		}, {
			"administrative_id": 33,
			"desc": "妇产科是临床医学四大主要学科之一，主要研究女性生殖器官疾病的病因、病理、诊断及防治，妊娠、分娩的生理和病理变化，高危妊娠及难产的预防和诊治，女性生殖内分分泌，计划生育及妇女保健等。\n",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "妇产科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 34,
			"desc": "儿科是全面研究小儿时期身心发育、保健以及疾病防治的综合医学科学。凡涉及儿童和青少年时期的健康与卫生问题都属于儿科范围。其医治对象处于生长发育期。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "儿科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 35,
			"desc": "放射科是医院重要的辅助检查科室，在现代医院建设中，放射科是一个集检查、诊断、治疗于一体的科室，临床各科许多疾病都须通过放射科设备检查达到明确诊断和辅助诊断。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "放射科",
			"parent_administrative_id": 34
		}, {
			"administrative_id": 36,
			"desc": "医院医疗科室之一，开展超声（二维超声、多普勒超声、介入超声、三维超声、造影）诊断与治疗",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "超声科",
			"parent_administrative_id": 34
		}, {
			"administrative_id": 37,
			"desc": "影像学不仅扩大了人体的检查范围，提高了诊断水平，而且可以对某引些疾病进行治疗。这样，就大大地扩展了本学科的工作内容，并成为医疗工作中的重要支柱。自伦琴（WilhelmConradRontgen）1895年发现X线以后不久，在医学上，X线就被用于对人体检查，进行疾病诊断，形成了放射诊断学（diagnosticradiology）的新学科，并奠定了医学影像学（medicalimageology）的基础。至今放射诊断学仍是医学影像学中的主要内容，应用普遍",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "医学影像科",
			"parent_administrative_id": 34
		}, {
			"administrative_id": 38,
			"desc": "传染病科是治疗传染病的部门。常见传染病有菌痢、伤寒、霍乱、甲型毒性肝炎、流脑、猩红热、百日咳、流感、麻疹、丝虫病、乙型脑炎、血吸虫病等。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "传染科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 39,
			"desc": "肝病科，是一个与许多科室交叉的学科，如感染科、消化内科、肝胆外科、普外科，其诊疗内容内、外兼顾，涉及范围较广。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "肝病科",
			"parent_administrative_id": 38
		}, {
			"administrative_id": 40,
			"desc": "口腔科，医学学科分类之一。主要口腔科疾病包括：口腔颌面部皮样、表皮颌下间隙感染、颌面部淋巴管瘤、齿状突发育畸形、上颌窦恶性肿瘤、颌骨造釉细胞瘤、慢性筛窦炎、下颌后缩、四环素牙、舌白斑等疾病。现在的技术，许多牙周病完全可以治愈。组织生物工程技术的发展如：引导组织再生技术、基因技术、种植义齿等更是为病变牙齿的再生带来令人振奋的希望。但牙周病的治疗必须是一个序列治疗。在治疗过程中制定一个详细、有效的治疗计划、医生细致精湛的治疗和病人的积极配合是治疗成功的关键。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "口腔科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 41,
			"desc": "以皮肤症状为主 ( 如梅毒、 软下疳、 尖锐湿疣、 生殖器疱疹等 ),因此 , 除专业防治机构外,在综合医院中常将性病诊疗业务归并到皮肤科,称为皮肤性.",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "皮肤性病科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 42,
			"desc": "皮肤科属于外科，主要治疗各种皮肤病，常见皮肤病有牛皮癣 、 疱疹 、酒渣鼻 、脓疱疮 、化脓菌感染 、疤痕 、癣 、鱼鳞病 、腋臭 、青春痘 、毛囊炎 、斑秃脱发 、男科炎症 、婴儿尿布疹 、鸡眼 、雀斑 、汗疱疹 、螨虫性皮炎 、白癜风 、湿疹 、灰指甲 、硬皮病 、皮肤瘙痒 、口腔部护理 、脱毛 、黄褐斑等",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "皮肤科",
			"parent_administrative_id": 41
		}, {
			"administrative_id": 43,
			"desc": "治疗性病的专业级科室，属于皮肤科",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "性病科",
			"parent_administrative_id": 41
		}, {
			"administrative_id": 44,
			"desc": "口腔科，医学学科分类之一。主要口腔科疾病包括：口腔颌面部皮样、表皮颌下间隙感染、颌面部淋巴管瘤、齿状突发育畸形、上颌窦恶性肿瘤、颌骨造釉细胞瘤、慢性筛窦炎、下颌后缩、四环素牙、舌白斑等疾病。现在的技术，许多牙周病完全可以治愈。组织生物工程技术的发展如：引导组织再生技术、基因技术、种植义齿等更是为病变牙齿的再生带来令人振奋的希望。但牙周病的治疗必须是一个序列治疗。在治疗过程中制定一个详细、有效的治疗计划、医生细致精湛的治疗和病人的积极配合是治疗成功的关键。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "口腔科",
			"parent_administrative_id": -1
		}, {
			"administrative_id": 45,
			"desc": "口腔修复，俗称镶牙，主要是针对牙齿缺损、牙齿缺失后的治疗工作，如嵌体、全冠、义齿等，也包括利用人工修复体针对牙周病、颞下颌关节病和颌面部组织缺损的治疗，如咬合板、牙周夹板、赝复体、义眼、义耳、义鼻等。是口腔医学中的一个重要分支，种植修复、粘结修复、美学修复是现代口腔修复发展最快的领域，显著提升了口腔修复的治疗效果和水平。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 2,
			"name": "口腔修复科",
			"parent_administrative_id": 44
		}, {
			"administrative_id": 46,
			"desc": "“耳鼻咽喉科”是诊断治疗耳、鼻、咽、喉、及其相关头颈区域的外科学科。随着科技的进步与发展，医学各科相互渗透和促进，拓展了耳鼻咽喉科的范畴，耳显微外科，耳神经外科，侧颅底外科，听力学及平衡科学，鼻内镜外科，鼻神经外科（鼻颅底外科），头颈外科，喉显微外科，嗓音与言语疾病科，小儿耳鼻咽喉科等的出现，大大丰富了耳鼻咽喉科的内容。",
			"hospital_id": 12,
			"hospital_name": "福州市医院",
			"is_display": true,
			"level": 1,
			"name": "耳鼻喉科",
			"parent_administrative_id": -1
		}]
	},
	"message": "SUCCESS"
}